all:
    children:
        control_plane:
            hosts:
                kubernetes-control-plane-1:
                    ansible_host: 95.216.40.254
                kubernetes-control-plane-2:
                    ansible_host: 95.216.10.90
                kubernetes-control-plane-3:
                    ansible_host: 78.46.77.43
        worker_nodes:
            hosts:
                kubernetes-worker-1:
                    ansible_host: 195.201.10.7
                kubernetes-worker-2:
                    ansible_host: 88.99.62.232
                kubernetes-worker-3:
                    ansible_host: 192.168.1.22
    vars:
        ansible_user: core
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
