name: Apply Manifests
on:
  push:
    branches: [ main ]
    paths: [ 'clusters/**' ]
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'
      - run: kubectl apply -k clusters/management-cluster/
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
